### ISSUE TITLE
Add lobby in submenu

### ISSUE THREAD

**Issue by MC-luoluo** [QWERTZexe/Quickjoin#2]
Some people may want to use quick join to join a game lobby, so I recommend adding a lobby button to the submenu. like this:
![Image](https://github.com/QWERTZexe/Quickjoin/assets/113677351/b73ed64a-6436-441a-bafc-7dc38c212000)

**Comment by MC-luoluo** [comment]
Join the bedwars lobby can use `/l bw`. Others are similar.

**Comment by QWERTZexe** [comment]
> Join the bedwars lobby can use `/l bw`. Others are similar.

I am considering this. If you made a PR with the changes in the json i would happily merge it!

**Comment by QWERTZexe** [comment]
@MC-luoluo Feature added ✅
